### ISSUE TITLE
Add support out of cluster client config

### ISSUE THREAD

**Issue by jhorwit2** [openshift/generic-admission-server#15]
Currently, the admission server is hard coded to load the in-cluster configuration, which restricts the server from be ran easily for development/testing/external to the server. 

https://github.com/openshift/generic-admission-server/blob/master/pkg/apiserver/apiserver.go#L126-L129

Would you be open to a new `New()` method named `NewWithClientConfig`. This would allow servers using this as an delegated apiserver to pass in the client configuration determined via cli args.

**Comment by deads2k** [comment]
In principle, yes, but how would you keep the construction unified. Perhaps a struct in this package that is an `AdmissionServerBuilder` with methods to `AddMutatingAdmission`, `AddValidatingAdmission`, `AddKubeConfigFile`, and finally `RunAdmissionServer` ?

**Comment by jhorwit2** [comment]
@deads2k `New` would call `NewWithClientConfig` immediately with the in-cluster config. The lines preceding the config call can be after which allows them to use the same code.

**Comment by deads2k** [comment]
> @deads2k New would call NewWithClientConfig immediately with the in-cluster config. The lines preceding the config call can be after which allows them to use the same code. (move the logic in New to NewWithClientConfig)

The main entry point is through this package `import "github.com/openshift/generic-admission-server/pkg/cmd"`, so I'd want to keep wiring accessible from that package unless there's a strong reason not to.

**Comment by jhorwit2** [comment]
```go
diff --git a/vendor/github.com/openshift/generic-admission-server/pkg/apiserver/apiserver.go b/vendor/github.com/openshift/generic-admission-server/pkg/apiserver/apiserver.go
index 36db7d0..818ac5f 100644
--- a/vendor/github.com/openshift/generic-admission-server/pkg/apiserver/apiserver.go
+++ b/vendor/github.com/openshift/generic-admission-server/pkg/apiserver/apiserver.go
@@ -76,6 +76,8 @@ func init() {
 type Config struct {
 	GenericConfig *genericapiserver.RecommendedConfig
 	ExtraConfig   ExtraConfig
+
+	clientConfig *restclient.Config
 }
 
 type ExtraConfig struct {
@@ -90,6 +92,8 @@ type AdmissionServer struct {
 type completedConfig struct {
 	GenericConfig genericapiserver.CompletedConfig
 	ExtraConfig   *ExtraConfig
+
+	clientConfig *restclient.Config
 }
 
 type CompletedConfig struct {
@@ -102,6 +106,7 @@ func (c *Config) Complete() CompletedConfig {
 	completedCfg := completedConfig{
 		c.GenericConfig.Complete(),
 		&c.ExtraConfig,
+		restclient.CopyConfig(c.GenericConfig.ClientConfig),
 	}
 
 	completedCfg.GenericConfig.Version = &version.Info{
@@ -109,7 +114,7 @@ func (c *Config) Complete() CompletedConfig {
 		Minor: "1",
 	}
 
-	return CompletedConfig{&completedCfg}
+	return CompletedConfig{completedConfig: &completedCfg}
 }
 
 // New returns a new instance of AdmissionServer from the given config.
@@ -123,11 +128,6 @@ func (c completedConfig) New() (*AdmissionServer, error) {
 		GenericAPIServer: genericServer,
 	}
 
-	inClusterConfig, err := restclient.InClusterConfig()
-	if err != nil {
-		return nil, err
-	}
-
 	for _, versionMap := range admissionHooksByGroupThenVersion(c.ExtraConfig.AdmissionHooks...) {
 		accessor := meta.NewAccessor()
 		versionInterfaces := &meta.VersionInterfaces{
@@ -205,7 +205,7 @@ func (c completedConfig) New() (*AdmissionServer, error) {
 		}
 		s.GenericAPIServer.AddPostStartHookOrDie(postStartName,
 			func(context genericapiserver.PostStartHookContext) error {
-				return admissionHook.Initialize(inClusterConfig, context.StopCh)
+				return admissionHook.Initialize(c.clientConfig, context.StopCh)
 			},
 		)
 	}
```

Could do something like that. Since the configuration already has the client config set when you do `ApplyTo` on the `RecommendedConfig`. Kinda seems a little hacky tho. Using the same idea, the cmd package would want to pass in the client configuration from RecommendedConfig as well which uses cli args to build the config (--kubeconfig, etc).

**Comment by deads2k** [comment]
actually, reading through, doesn't this https://github.com/openshift/generic-admission-server/blob/master/pkg/cmd/server/start.go#L85 already apply the options specified by the command added here https://github.com/openshift/generic-admission-server/blob/master/pkg/cmd/server/start.go#L65 ?

**Comment by jhorwit2** [comment]
Yup! The patch I posted uses that client config created. It's just not available when you call `New` currently because it's not added to the `(Cc)ompletedConfig`'s.

**Comment by deads2k** [comment]
> Yup! The patch I posted uses that client config created. It's just not available when you call New currently because it's not added to the (Cc)ompletedConfig's.

Weird.  Seems like a shortcoming upstream.  Open a pull?

**Comment by jhorwit2** [comment]
Yeah, i'll open one @deads2k.

**Comment by jhorwit2** [comment]
@deads2k just making sure, this what you were thinking? https://github.com/kubernetes/kubernetes/compare/master...jhorwit2:jah/restclient-apiconfig

**Comment by deads2k** [comment]
> @deads2k just making sure, this what you were thinking? kubernetes/kubernetes@master...jhorwit2:jah/restclient-apiconfig

Yeah.  I think you need to be clear it's pointing to the kube-apiserver (it is, isn't it?), but I suspect that many apiservers will find it useful.
