### ISSUE TITLE
Bug: Kind should be provided from ***Hook interface

### ISSUE THREAD

**Issue by tamalsaha** [openshift/generic-admission-server#9]
Hi @deads2k , I noticed that Kind is hardcoded to `AdmissionReview` in https://github.com/openshift/generic-admission-server/blob/master/pkg/apiserver/apiserver.go#L174

Should this be provided from the **Hook interface, since users of this library can define the singular and plural form the resource.

**Comment by deads2k** [comment]
The Kind is hardcoded because `AdmissionReview` is the only valid thing to send to an admission webhook endpoint.  The Resource (the URL) can be different, but the Kind (the data format) is always an AdmissionReview

**Comment by tamalsaha** [comment]
I tried adding a second webhook. Here is my code:
https://github.com/tamalsaha/kubernetes-namespace-reservation/commit/4fbcd77fbbe695a8c3fed6a9c3c19ac9acad4e36

But I am getting the following error message:
```
[restful] WebService with duplicate root path detected:

[restful] 2018/02/10 21:44:23 log.go:33: [restful] WebService with duplicate root path detected:['&{/apis/admission.online.openshift.io/v1beta1 0xc420411e80 [{POST [application/json application/yaml application/vnd.kubernetes.protobuf] [*/*] /apis/admission.online.openshift.io/v1beta1/seconds 0xf192d0 [] seconds [apis admission.online.openshift.io v1beta1 seconds] 0xc4202ff680 create an AdmissionReview  createAdmissionReview [0xc42000e690 0xc42000e6a0] map[200:{200 OK {{ } <nil> <nil>} false} 201:{201 Created {{ } <nil> <nil>} false} 202:{202 Accepted {{ } <nil> <nil>} false}] {{ } <nil> <nil>} {{ } <nil> <nil>} map[x-kubernetes-action:post x-kubernetes-group-version-kind:{admission.k8s.io v1beta1 AdmissionReview}]} {GET [application/json application/yaml application/vnd.kubernetes.protobuf] [application/json application/yaml application/vnd.kubernetes.protobuf] /apis/admission.online.openshift.io/v1beta1/ 0xf22290 [] / [apis admission.online.openshift.io v1beta1] 0xc4202ffdc0 get available resources  getAPIResources [] map[] <nil> {{ }  []} map[]}] [application/json application/yaml application/vnd.kubernetes.protobuf application/json;stream=watch application/vnd.kubernetes.protobuf;stream=watch] [*/*] [] [] API at /apis/admission.online.openshift.io/v1beta1 admission.online.openshift.io/v1beta1 <nil> false {{0 0} 0 0 0 0}}']
```

This seems to be coming from the go-restful library: https://github.com/emicklei/go-restful/blob/master/container.go#L100

How do I add 2 separate `AdmissionReview` kind as 2 different resource in the same apiVersion?
